README.md, link_telemetry.py
If the `--randomize` switch is used, `--frequency-hz` allows user to set the frequency at which random messages are generated.
=> Add --frequency-hz switch to `link_telemetry.py`

dbc/brightside.dbc
Add brightside dbc pending a few additional CAN messages to be added.
=> add brightside dbc

README.md, docker-compose.yaml, link_telemetry.py, parser/main.py, provisioning/datasources/datasource.yaml
Timestamp field also added for offline mode.
=> feat: Prod Bucket changed to CAN Bucket

README.md, link_telemetry.py
Only changes in the latest commit inside the link_telemetry.py file need to be pulled in. Just made changes to the log_upload function and the main to fix some small errors when trying to read the SD logger.
=> fixed log upload

dbc/brightside.dbc
**Addition:**
* 64 bit githash signal for MCB message 0x405. Based on CAN ID table docs.
=> Add: MCB Githash ID = 0x405 to DBC

dashboards/Pit Crew Dashboard-1711352544498.json
- Updated Pit Crew Dashboard to have labels for the MCB Drive State 
- Updated source bucket for IMU data in Pit Crew Dashboard
N/A
=> fix: Update Pit Crew Dashboard

dashboards/LOG/LOG_ Pit Crew - Brightside-1719524880537.json, dashboards/PROD/PROD_ BMS - Brightside-1719524891796.json, dashboards/PROD/PROD_ MC (Mitsuba) - Brightside-1719524897337.json, dashboards/PROD/PROD_ MCB - Brightside-1719524903423.json, dashboards/PROD/PROD_ PAS - Brightside-1719524907714.json, dashboards/PROD/PROD_ Pit Crew - Brightside-1719524913369.json, dashboards/TEST/TEST_ Pit Crew - Brightside-1719524926339.json
Added units to all dashboards which needs them.
=> Fix: Added units to dashboards

README.md, setup.sh
Fixed the curl link in README + fixed typo.
=> fix: changed curl command to download setup.sh

setup.sh
Added buckets for atl atr test and prod.
=> feat: atl and atr prod and test buckets

README.md
Since the setup script handles everything users were confused if the steps after the setup script were applicable to them. As such the README was fixed and refactored so that the later parts talking about setting up environment variables, token, etc, are just explanations for what the script does and why.
This is based on feedback from Maka after trying the script.
=> Fix: Updated README to support setup script handling everything already.

scripts/CSV_Download_script.sh
Old Token expired. Instead of hard coding the token I ask the user for the token now.
I ran the CSV download script with the changes and worked perfectly as expected.
=> Feat: Ask for InfluxDB token instead of putting in the repository

dbc/brightside.dbc
Noticed a problem with CPU Load. Its always 100 Removing this feature and adding issue in firmware v3
=> Feat: Added CAN Bus Load and CPU Load

dbc/brightside.dbc
=> Feat: Updated GPS DBC file

dbc/brightside.dbc
=> Fix: Clean DBC and update 0x401

dbc/brightside.dbc
=> Feat: Dbc watchdog heartbeat add

dbc/brightside.dbc, parser/main.py
=> Feat: Rpm to speed

tools/MemoratorUploader.py
=> Fix: Changed ch0 to ch1 for memorator upload script

dashboards/LOG/LOG_Pit_Crew_Brightside.json, dashboards/PROD/PROD_BMS _Brightside.json, dashboards/PROD/PROD_Pit_Crew_Brightside.json, dashboards/TEST/TEST_Pit_Crew_Brightside.json
=> Feat: Diagostic messages in pit crew dashboard

dashboards/LOG/LOG_Pit_Crew_Brightside.json, dashboards/PROD/PROD_BMS_Brightside.json, dashboards/PROD/PROD_DRD_Brightside.json, dashboards/PROD/PROD_MC_(Mitsuba)_Brightside.json, dashboards/PROD/PROD_MDI_Brightside.json, dashboards/PROD/PROD_Pit_Crew_Brightside.json, dashboards/PROD/PROD_STR_Brightside.json, dashboards/PROD/PROD_TEL_Brightside.json, dashboards/TEST/TEST_Pit_Crew_Brightside.json
=> Feat: More Grafana Updates

dashboards/LOG/LOG_Pit_Crew_Brightside.json, dashboards/PROD/PROD_MPPT_Brightside.json, dashboards/PROD/PROD_Pit_Crew_Brightside.json, dashboards/TEST/TEST_Pit_Crew_Brightside.json, dbc/brightside.dbc
=> Feat: MPPT DBC + Grafana

dbc/brightside.dbc
Added the Horn Pin to STR including the CAN message
=> Feat: Added the Horn Pin to STR

dbc/brightside.dbc
=> Feat: Fixed DBC for Cyclic Data Diagnostic Message

scripts/csv_upload.sh
=> Fixed script of electrical bay computer upload.

dashboards/LOG/LOG_Pit_Crew_Brightside.json, dashboards/PROD/PROD_BMS_Brightside.json, dashboards/PROD/PROD_MC_(Mitsuba)_Brightside.json, dashboards/PROD/PROD_MPPT_Brightside.json, dashboards/PROD/PROD_Pit_Crew_Brightside.json, dashboards/PROD/PROD_TEL_Brightside.json, dashboards/TEST/TEST_Pit_Crew_Brightside.json
=> Updated Grafana dashboards with decimals

dashboards/PROD/PROD_MPPT_Brightside.json
=> Updated mppt dash

README.md, tools/MemoratorUploader.py
=> Added upload command in README
